services:
  cloud:
    container_name: cloud
    image: ghcr.io/d-hooper/simple_server:latest
    ports:
      - "8090:3000"
    env_file:
      - .env.cloud-infrastructure-lab
    labels:
      caddy.domain: cloud.dallinhooper.com
