services:
  quick:
    container_name: quick
    image: ghcr.io/d-hooper/simple_server:latest
    ports:
      - "7045:8080"
    env_file:
      - .env.cloud-infrastructure-lab
    labels:
      caddy.domain: cloud.dallinhooper.com
